### ISSUE TITLE
Enable Sign in with Apple

### ISSUE THREAD

**Issue by juanlaube** [toggl/watchos-app#135]
## 🎯 What needs to be done?
This is to prepare Sign in with Apple for the watchOS app

## 📝 Detailed explanation
1. Enable Sign in with Apple on all the watchOS AppIDs with `com.toggl.daneel` as the primary AppID
1. Add the required app entitlement to the target
1. Link AccountServices.framework

**Comment by Odrakir** [comment]
Oh... Now that I'm reading this... The watch app has a totally different bundle id, will this work? 🤔

**Comment by juanlaube** [comment]
Yep, this should work fine as long as all apps are under the same team.

**Comment by juanlaube** [comment]
I've enabled the feature in the app ids and generated the provisioning profiles again.
